# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd955db8336f401cf64a3a3af332096448bca274d2426b09825253e592e47c9baee862f0ee35b8caaf95a9e5698db1d19c3f45e53c2b689fdac742928a354551

test:
  secret_key_base: 5fd76c37dbdf004a136b1d4127302a2aa5173a8d728d470740742368c6153d2303e2089b430288f1c5f2f3fad92f4dda5079a01cc2b916a647b2b10729cf4744

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
